### ISSUE TITLE
Red fog

### ISSUE THREAD

**Issue by liach** [3TUSK/CustomFog#1]
https://github.com/3TUSK/CustomFog/blob/master/src/main/java/tritusk/customfog/CustomFog.java#L36-L39

Change that code to fix red fog I think?

**Comment by 3TUSK** [comment]
That red fog *is* test in order to see that event is available. Beside, this project *is* an accident.

**Comment by 3TUSK** [comment]
In another word, it *is* on purpose.

**Comment by liach** [comment]
A new modpack?

**Comment by 3TUSK** [comment]
Basically a tool for modpack creator. Imagine that you *have to* survive in a world filled with thick fog. (What a heck?!)

**Comment by 3TUSK** [comment]
@liach Have you heard about *EoSD*?

**Comment by liach** [comment]
?

**Comment by 3TUSK** [comment]
Seems that you haven't heard about EoSD. Google it and you will probably *be* able to understand the "red fog".
